# Generated by Django 3.2.6 on 2022-12-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20221226_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='background_colour',
        ),
        migrations.RemoveField(
            model_name='task',
            name='site_name',
        ),
    ]
