# Generated by Django 3.2.6 on 2022-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20221226_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='background_colour',
            field=models.CharField(default='lemon', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='site_name',
            field=models.CharField(default='Krafta', max_length=255),
        ),
    ]
