# Generated by Django 3.2.6 on 2022-12-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='site_name',
        ),
    ]
